name: "Test and Lint"
on:
    push:
        branches-ignore:
            - 'main'
env:
    GO_VERSION: '1.22.4'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - uses: actions/setup-go@v2
              with:
                go-version: $GO_VERSION
            - name: Lint
              run: |
                go mod tidy
                make fmt
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - uses: actions/setup-go@v2
              with:
                go-version: $GO_VERSION
            - name: Lint
              run: |
                go test -v ./...

